name: 'Sinch Conversation API'

description: 'Send a message from Github Actions using the Sinch Conversation API'

branding:
  icon: 'message-square'
  color: 'yellow'

inputs:
  clientId:
    description: 'Sinch clientId'
    required: true

  clientSecret:
    description: 'Sinch clientSecret'
    required: true

  projectId:
    description: 'Sinch projectId'
    required: true

  appId:
    description: 'Sinch appId'
    required: true

  message:
    description: 'Message to send'
    required: true

  meta:
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
