# This is a basic workflow to help you get started with Actions

name: Test pipeline

# Controls when the workflow will run 
on: [repository_dispatch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        run: yarn build

      - name: Send messages
        run: yarn run send:messages
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          PROJECT_ID: ${{secrets.PROJECT_ID}}
          APP_ID: ${{secrets.APP_ID}}
